# Generated by Django 3.2 on 2021-04-07 04:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('stars', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('is_for_all', models.BooleanField(default=False)),
                ('student1', models.CharField(max_length=100)),
                ('student2', models.CharField(max_length=100)),
                ('student3', models.CharField(max_length=100)),
            ],
        ),
    ]
