# Generated by Django 3.2 on 2021-04-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0002_auto_20210407_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questboard',
            name='is_for_everyone',
            field=models.BooleanField(default=False, verbose_name='Is the quest for everyone?'),
        ),
        migrations.AlterField(
            model_name='questboard',
            name='student1',
            field=models.CharField(blank=True, max_length=100, verbose_name='First Student'),
        ),
        migrations.AlterField(
            model_name='questboard',
            name='student2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Second Student'),
        ),
        migrations.AlterField(
            model_name='questboard',
            name='student3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Third Student'),
        ),
    ]
