# Generated by Django 3.2 on 2021-04-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0004_alter_questboard_is_for_everyone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questboard',
            name='is_for_everyone',
            field=models.BooleanField(default=False, verbose_name='The Quest is for Everyone'),
        ),
    ]
