# Generated by Django 3.2 on 2021-04-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0005_alter_questboard_is_for_everyone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questboard',
            new_name='QuestCard',
        ),
    ]
