# Generated by Django 3.2 on 2021-04-07 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questboard', '0006_rename_questboard_questcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('required_stars', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RenameField(
            model_name='questcard',
            old_name='name',
            new_name='quest_name',
        ),
    ]
